CONST 
(* ------------------------------------------------------------------------ *)

{Object wear mnemons}
	ow_notequippable = 0;
	ow_swordhand = 1;
	ow_shieldhand = 2;
	ow_twohand = 3;
	ow_body = 4;
	ow_head = 5;
	ow_eyes = 6;
	ow_neck = 7;
	ow_back = 8;
	ow_upertorso = 9;
	ow_arms = 10;
	ow_wrist = 11;
	ow_ring = 12;
	ow_hand = 13;
	ow_waist = 14;
	ow_legs = 15;
	ow_feet = 16;
	ow_backpack = 17;
	ow_pouch = 18;
	ow_quiver = 19;

(* ------------------------------------------------------------------------ *)

{Effects for weapon parameters}
	ef_group	= 1;
	ef_class	= 2;
	ef_basehealth	= 3;
	ef_levelhealth	= 4;
	ef_basemana	= 5;
	ef_levelmana	= 6;
	ef_basesteal	= 7;
	ef_levelsteal	= 8;
	ef_movesilent	= 9;
	ef_levelmovesilent= 10;
	ef_movespeed	= 11;
	ef_healspeed	= 12;
	ef_attackspeed	= 13;
	ef_basedamage	= 14;
	ef_randomdamage	= 15;
	ef_leveldamage	= 16;
        ef_castspell    = 17;
	ef_experience	= 18;
	ef_weaponusage	= 19;
	ef_size		= 20;
	ef_hearnoise	= 21;
	ef_levelweaponusage= 22;
	ef_poison	= 23;
	ef_control	= 24;
	ef_invisible	= 25;
	ef_seeinvisible = 26;
	ef_weaponbasedamage= 27;
	ef_weaponrandomdamage= 28;
	ef_basearmor	= 29;
	ef_deflectarmor	= 30;
	ef_spellarmor	= 31;
        ef_sfit		= 32;
	ef_lfit		= 33;
	ef_condition	= 34;
	ef_breakchance	= 35;
	ef_breakmagnitude= 36;
        ef_charges	= 37;
        ef_spell	= 38;
	ef_spelldestroy	= 39;
        ef_throwbase	= 40;
	ef_throwrandom	= 41;
	ef_throwrange	= 42;
	ef_throwbehavior= 43;
	ef_cursed	= 44;


	ef_nothrow	= 47;
	ef_bombbase	= 48;
	ef_bombrandom	= 49;
	ef_bombtime	= 50;

	ef_trap		= 52;




	ef_dropdestroy	= 57;
        ef_crystalradius = 58;
	ef_teleport	= 59;


