/* DISK$USERDISK1:[MAS0.MASMONST.WORK]MONLOOKUP.H generated from DISK$USERDISK1:[MAS0.MASMONST.WORK]MONLOOKUP.PAS
   by unix XDPS$PSWRAP.EXE V1.009  Wed Apr 19 17:50:24 PDT 1989
 */

#ifndef MONLOOKUP_H
#define MONLOOKUP_H

#endif MONLOOKUP_H
